### PR TITLE
Add terraform show command

### PR DESCRIPTION
**Pull request by jesusbv**
Add show to the list of commands available

Add json option to show command

### CODE REVIEW

**Comment by tobyclemson** [comment]
Looks good to me.

**Comment by tobyclemson** [comment]
Are you ready for a merge?

**Comment by jesusbv** [comment]
> Are you ready for a merge?

I think so, forgot to update `README` before. 
It's good IMO.

**Comment by tobyclemson** [comment]
Ok, I'll run a release through shortly.

**Comment by tobyclemson** [comment]
Version [0.48.0](https://rubygems.org/gems/ruby-terraform/versions/0.48.0) has this change.

Thanks!

**Pull request merged**
