### PR TITLE
Adding support for -input option on plan and apply commands.

### PR DESCRIPTION
**Pull request by MAPontes**
Hi Toby,

I implemented the change we talked about on [#4](https://github.com/infrablocks/ruby_terraform/issues/4). I felt bad asking you for the feature and not helping in any way haha. I'm pretty new to git and ruby so I apologize for any mistakes. Hope it helps.

Thanks,
Marcelo Araújo Pontes

### CODE REVIEW

**Comment by tobyclemson** [comment]
Hi Marcelo,

Thanks for the pull request :) It looks good to me. Would you mind also updating the README to reflect the additional option?

Thanks,
Toby

**Comment by MAPontes** [comment]
Hey Toby,

No problem :). I also included documentation for the plan command.

Thanks,
Marcelo Araújo Pontes

**Comment by tobyclemson** [comment]
Merging in now, will release a new version shortly.

**Comment by tobyclemson** [comment]
v0.11.0 includes this change.

**Pull request merged**
