### PR TITLE
Make stdN configurable

### PR DESCRIPTION
**Pull request by jesusbv**
stdin, stdout and stderr can be set from the consumer

### CODE REVIEW

**Comment by tobyclemson** [comment]
Hey Jesus,

Thanks for this, it’s been requested by a few people so they’ll be pleased :)

I’ll get this merged in once I’m back at keyboard. It would be great to update the README and add some tests. I know the configuration stuff hasn’t really got tests there yet but even so.

Thanks,
Toby

**Comment by jesusbv** [comment]
> Hey Jesus,
> 
> Thanks for this, it’s been requested by a few people so they’ll be pleased :)
Yes, I thought to update the PR with the `Fixes #N ` (12 I think)
> 
> I’ll get this merged in once I’m back at keyboard. It would be great to update the README and add some tests. I know the configuration stuff hasn’t really got tests there yet but even so.
> 
No problem about the tests. The update of the README is in the to do list.
> Thanks,
> Toby

**Comment by jesusbv** [comment]
When approved, I would like to squash the commits into one before the merge

**Comment by tobyclemson** [comment]
Happy to merge, please go ahead and squash.

**Comment by tobyclemson** [comment]
Hey Jesus,

Sorry, I merged this prematurely. Don't worry about squashing the commits.

Thanks,
Toby

**Comment by jesusbv** [comment]
Thanks ! Good that is merged. It's not that relevant for this PR, it would be nice to keep a clean, nice log

In case you wanted to squash them on `master`, running `git rebase -i HEAD~1` would fix that.

**Comment by tobyclemson** [comment]
Looks like the configuration tests are failing, the merge failed through
CI. I’m out all day today but can take a look this evening.

**Comment by jesusbv** [comment]
Fixed.

**Comment by tobyclemson** [comment]
Thanks. Will merge later.

**Comment by tobyclemson** [comment]
Version [0.30.0](https://rubygems.org/gems/ruby-terraform/versions/0.30.0) includes this change.

**Pull request merged**
