### PR TITLE
Set logger to default value

### PR DESCRIPTION
**Pull request by jesusbv**

### CODE REVIEW

**Comment by tobyclemson** [comment]
Still have one failure but I'm gonna merge this in and update the tests. Thanks!

**Comment by jesusbv** [comment]
Weird. I know where the error comes from and how to fix it but...neither master nor the branch have it or are able to replicate it.

**Comment by tobyclemson** [comment]
Hey Jesus,

The error is because the minimum supported version of Ruby for the library is 2.3.8 so I'm testing with that version and the particular constructor of Logger you were using was introduced after that version.

I've made some fixes locally and will push through and release a release version of the library shortly.

Thanks,
Toby

**Comment by tobyclemson** [comment]
I've actually bumped the minimum supported version to 2.4.x now since 2.3 is no longer supported by the Ruby core team. You can see how I resolved the issues in master.

Version [0.30.0](https://rubygems.org/gems/ruby-terraform/versions/0.30.0) includes this change.

**Comment by jesusbv** [comment]
> I've actually bumped the minimum supported version to 2.4.x now since 2.3 is no longer supported by the Ruby core team. You can see how I resolved the issues in master.
> 
Yes, I saw. Great.

> Version [0.30.0](https://rubygems.org/gems/ruby-terraform/versions/0.30.0) includes this change.
>
Good, now consumers can configure their streams, and the wrapper is more flexible.

**Comment by tobyclemson** [comment]
> Good, now consumers can configure their streams, and the wrapper is more flexible.

Thanks for all your help!

**Pull request merged**
